export enum ReportResponseType {
  ERROR_REPORT = 'ERROR_REPORT',
  ERROR_COMPETENCY_REPORT = 'ERROR_COMPETENCY_REPORT',
  ERROR_JOB_REPORT = 'ERROR_JOB_REPORT',

  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
}
