export enum StoreKeys {
  REPORT = 'REPORT',
  TYPE_REPORT = 'TYPE_REPORT',
  LAST_REPORT_DATA = 'LAST_REPORT_DATA',
  JOBS_BY_CATEGORY = 'JOBS_BY_CATEGORY',
  JOB_CATEGORY = 'JOB_CATEGORY',
  USER_LOGO = 'USER_LOGO',
  USER_ROLES = 'USER_ROLES',
  USER_IS_ANONYMOUS = 'USER_IS_ANONYMOUS',

  SELECTED_BASE_ID = 'SELECTED_BASE_ID',
  SELECTED_SUBBASE_ID = 'SELECTED_SUBBASE_ID',

  USER_ID = 'USER_ID',
  USER_USERNAME = 'USER_USERNAME',

  SELECTED_INDIVIDUALS = 'SELECTED_INDIVIDUALS',
  SELECTED_JOB = 'SELECTED_JOB',
  SELECTED_JOB_CATEGORY = 'SELECTED_JOB_CATEGORY',
  SELECTED_INDIVIDUALS_BY_GROUP = 'SELECTED_INDIVIDUALS_BY_GROUP',
  PRESELECTED_IDS = 'PRESELECTED_IDS',
}
