export enum TypesInternalReports {
  HIRING_SURVEY = 'HIRING_SURVEY',
  HIRING_CANDIDATE_REVIEW = 'HIRING_CANDIDATE_REVIEW',
  HIRING_REPORT = 'HIRING_REPORT',
  DEVELOPMENT_SURVEY = 'DEVELOPMENT_SURVEY',
  DEVELOPMENT_CANDIDATE_REVIEW = 'DEVELOPMENT_CANDIDATE_REVIEW',
  DEVELOPMENT_REPORT = 'DEVELOPMENT_REPORT',
}
