import { StoreKeys } from '../../consts/store-keys.enum';

export const STORAGE_CONFIGURATION = [
  StoreKeys.MY_GENERATED_REPORT,
  StoreKeys.JOBS_BY_CATEGORY,
  StoreKeys.JOB_CATEGORY,
  StoreKeys.SELECTED_INDIVIDUALS,
  StoreKeys.SELECTED_JOB,
  StoreKeys.SELECTED_JOB_CATEGORY,
  StoreKeys.SELECTED_INDIVIDUALS_BY_GROUP,
  StoreKeys.PRESELECTED_IDS,
  StoreKeys.SELECTED_INDIVIDUALS_IDS_BY_AREA,
  StoreKeys.SELECTED_LEADER_ID_BY_AREA,
  StoreKeys.SELECTED_AREA_ID,
  StoreKeys.SELECTED_COMPETENCIES,
  StoreKeys.SELECTED_HRFEEDBACK,
  StoreKeys.REPORT_TEMPLATE_CONFIGURATION,
];
